org.gradle.jvmargs=-Xms512m -Xmx4g -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError
org.gradle.parallel=false
org.gradle.workers.max=2
android.useAndroidX=true
android.enableJetifier=true
android.bundle.enableUncompressedNativeLibs=true

kotlin.daemon.jvm.options=-Xms256m,-Xmx2g
