class DzikirItem {
  final int id;
  final String judul;
  final String arab;
  final String transliterasi;
  final String arti;
  final String faedah;
  final int targetCount;
  final String waktu; // 'pagi', 'petang', 'keduanya'

  const DzikirItem({
    required this.id,
    required this.judul,
    required this.arab,
    required this.transliterasi,
    required this.arti,
    required this.faedah,
    this.targetCount = 1,
    required this.waktu,
  });
}

class DzikirRepository {
  static const List<DzikirItem> dzikirPagiList = [
    DzikirItem(
      id: 1,
      judul: 'Membaca Ayat Kursi',
      arab: 'اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۗ مَنْ ذَا الَّذِي يَشْفَعُ عِنْدَهُ إِلَّا بِإِذْنِهِ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۖ وَلَا يُحِيطُونَ بِشَيْءٍ مِنْ عِلْمِهِ إِلَّا بِمَا شَاءَ ۚ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ ۖ وَلَا يَئُودُهُ حِفْظُهُمَا ۚ وَهُوَ الْعَلِيُّ الْعَظِيمُ',
      transliterasi: 'Allahu laa ilaaha illaa huwal hayyul qayyuum, laa ta’khudzuhuu sinatuw walaa na’um, lahuu maa fis-samaawaati wa maa fil-ardh, man dzalladzii yasyfa’u ‘indahuu illaa bi-idznih, ya’lamu maa baina aydiihim wa maa khalfahum, wa laa yuhiithuuna bisyai-im min ‘ilmihii illaa bimaa syaa-a, wasi’a kursiyyuhus-samaawaati wal-ardh, wa laa ya-uuduhuu hifzhuhumaa, wa huwal ‘aliyyul ‘azhiim.',
      arti: 'Allah, tidak ada tuhan selain Dia. Yang Mahahidup, Yang terus-menerus mengurus (makhluk-Nya), tidak mengantuk dan tidak tidur. Milik-Nya apa yang ada di langit dan apa yang ada di bumi. Tidak ada yang dapat memberi syafaat di sisi-Nya tanpa izin-Nya. Dia mengetahui apa yang ada di hadapan mereka dan apa yang ada di belakang mereka, dan mereka tidak mengetahui sesuatu apa pun tentang ilmu-Nya melainkan apa yang Dia kehendaki. Kursi-Nya meliputi langit dan bumi. Dan Dia tidak merasa berat memelihara keduanya, dan Dia Mahatinggi, Mahabesar.',
      faedah: 'Barangsiapa membacanya di pagi hari, ia akan dilindungi dari gangguan jin hingga petang hari. (HR. Al-Hakim 1:562, Shahih At-Targhib no. 655)',
      targetCount: 1,
      waktu: 'pagi',
    ),
    DzikirItem(
      id: 2,
      judul: 'Membaca Surat Al-Ikhlas, Al-Falaq, An-Naas',
      arab: 'قُلْ هُوَ اللَّهُ أَحَدٌ ﴿١﴾ اللَّهُ الصَّمَدُ ﴿٢﴾ لَمْ يَلِدْ وَلَمْ يُولَدْ ﴿٣﴾ وَلَمْ يَكُنْ لَهُ كُفُوًا أَحَدٌ ﴿٤﴾\n\nقُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ﴿١﴾ مِنْ شَرِّ مَا خَلَقَ ﴿٢﴾ وَمِنْ شَرِّ غَاسِقٍ إِذَا وَقَبَ ﴿٣﴾ وَمِنْ شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ ﴿٤﴾ وَمِنْ شَرِّ حَاسِدٍ إِذَا حَسَدَ ﴿٥﴾\n\nقُلْ أَعُوذُ بِرَبِّ النَّاسِ ﴿١﴾ مَلِكِ النَّاسِ ﴿٢﴾ إِلَٰهِ النَّاسِ ﴿٣﴾ مِنْ شَرِّ الْوَسْوَاسِ الْخَنَّاسِ ﴿٤﴾ الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ ﴿٥﴾ مِنَ الْجِنَّةِ وَالنَّاسِ ﴿٦﴾',
      transliterasi: 'Membaca surat Al-Ikhlas, Al-Falaq, dan An-Naas masing-masing sebanyak 3 kali.',
      arti: 'Dengan menyebut nama Allah Yang Maha Pengasih lagi Maha Penyayang. (Surat Al-Ikhlas, Al-Falaq, dan An-Naas).',
      faedah: 'Barangsiapa membacanya sebanyak 3 kali ketika pagi dan petang hari, maka segala sesuatu akan dicukupkan untuknya dan terlindung dari segala keburukan. (HR. Abu Daud no. 5082, Tirmidzi no. 3575)',
      targetCount: 3,
      waktu: 'pagi',
    ),
    DzikirItem(
      id: 3,
      judul: 'Doa Memasuki Waktu Pagi',
      arab: 'أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ، رَبِّ أَسْأَلُكَ خَيْرَ مَا فِي هَٰذَا الْيَوْمِ وَخَيْرَ مَا بَعْدَهُ، وَأَعُوذُ بِكَ مِنْ شَرِّ مَا فِي هَٰذَا الْيَوْمِ وَشَرِّ مَا بَعْدَهُ، رَبِّ أَعُوذُ بِكَ مِنَ الْكَسَلِ وَسُوءِ الْكِبَرِ، رَبِّ أَعُوذُ بِكَ مِنْ عَذَابٍ فِي النَّارِ وَعَذَابٍ فِي الْقَبْرِ',
      transliterasi: 'Ash-bahnaa wa ash-bahal mulku lillaahi wal hamdu lillaah, laa ilaaha illallaahu wahdahu laa syariika lah, lahul mulku wa lahul hamdu wa huwa ‘alaa kulli syai-in qadiir. Rabbi as-aluka khaira maa fii haadzal yaumi wa khaira maa ba’dah, wa a’uudzu bika min syarri maa fii haadzal yaumi wa syarri maa ba’dah. Rabbi a’uudzu bika minal kasali wa suu-il kibar, Rabbi a’uudzu bika min ‘adzaabin fin-naari wa ‘adzaabin fil qabr.',
      arti: 'Kami telah memasuki waktu pagi dan kerajaan hanya milik Allah, segala puji bagi Allah. Tidak ada ilah yang berhak disembah selain Allah semata, tiada sekutu bagi-Nya. Milik-Nya kerajaan dan bagi-Nya pujian. Dia Mahakuasa atas segala sesuatu. Wahai Rabbku, aku memohon kepada-Mu kebaikan hari ini dan kebaikan setelahnya, dan aku berlindung kepada-Mu dari kejahatan hari ini dan kejahatan setelahnya. Wahai Rabbku, aku berlindung kepada-Mu dari kemalasan dan keburukan di hari tua. Wahai Rabbku, aku berlindung kepada-Mu dari siksaan di neraka dan siksaan di kubur.',
      faedah: 'Memohon kebaikan hari dan perlindungan dari keburukan, rasa malas, serta siksa kubur dan api neraka. (HR. Muslim no. 2723)',
      targetCount: 1,
      waktu: 'pagi',
    ),
    DzikirItem(
      id: 4,
      judul: 'Sayyidul Istighfar',
      arab: 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَٰهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَىٰ عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ',
      transliterasi: 'Allaahumma anta rabbii laa ilaaha illaa anta, khalaqtanii wa anaa ‘abduka, wa anaa ‘alaa ‘ahdika wa wa’dika mastatha’tu, a’uudzu bika min syarri maa shana’tu, abuu-u laka bini’matika ‘alayya, wa abuu-u bidzanbii faghfir lii fa-innahu laa yaghfirudz-dzunuuba illaa anta.',
      arti: 'Ya Allah, Engkau adalah Rabbku, tiada tuhan selain Engkau. Engkaulah yang menciptakanku dan aku adalah hamba-Mu. Aku akan setia pada perjanjianku dengan-Mu semampuku. Aku berlindung kepada-Mu dari keburukan yang telah kuperbuat. Aku mengakui nikmat-Mu kepadaku dan aku mengakui dosaku, maka ampunilah aku, sesungguhnya tiada yang dapat mengampuni dosa selain Engkau.',
      faedah: 'Barangsiapa mengucapkannya di waktu pagi dengan penuh keyakinan lalu meninggal sebelum sore hari, maka ia termasuk penghuni surga. (HR. Bukhari no. 6306)',
      targetCount: 1,
      waktu: 'pagi',
    ),
    DzikirItem(
      id: 5,
      judul: 'Doa Perlindungan Pagi Hari',
      arab: 'اللَّهُمَّ بِكَ أَصْبَحْنَا، وَبِكَ أَمْسَيْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ النُّشُورُ',
      transliterasi: 'Allaahumma bika ash-bahnaa, wa bika amsainaa, wa bika nahyaa, wa bika namuutu, wa ilainkan-nusyuur.',
      arti: 'Ya Allah, dengan rahmat-Mu kami memasuki waktu pagi, dengan rahmat-Mu kami memasuki waktu sore, dengan rahmat-Mu kami hidup dan dengan rahmat-Mu kami mati, serta kepada-Mulah tempat kembali (kebangkitan).',
      faedah: 'Doa penyerahan diri dan syukur atas kehidupan di pagi hari. (HR. Tirmidzi no. 3391, Abu Daud no. 5068)',
      targetCount: 1,
      waktu: 'pagi',
    ),
    DzikirItem(
      id: 6,
      judul: 'Memohon Keselamatan & Afiat',
      arab: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَافِيَةَ فِي الدُّنْيَا وَالْآخِرَةِ، اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَفْوَ وَالْعَافِيَةَ فِي دِينِي وَدُنْيَايَ وَأَهْلِي وَمَالِي، اللَّهُمَّ اسْتُرْ عَوْرَاتِي وَآمِنْ رَوْعَاتِي، اللَّهُمَّ احْفَظْنِي مِنْ بَيْنِ يَدَيَّ وَمِنْ خَلْفِي وَعَنْ يَمِينِي وَعَنْ شِمَالِي وَمِنْ فَوْقِي، وَأَعُوذُ بِعَظَمَتِكَ أَنْ أُغْتَالَ مِنْ تَحْتِي',
      transliterasi: 'Allaahumma innii as-alukal ‘aafiyata fid-dunyaa wal aakhirah. Allaahumma innii as-alukal ‘afwa wal ‘aafiyata fii diinii wa dunyaaya wa ahlii wa maalii. Allaahummastur ‘awraatii wa aamin raw’aatii. Allaahummah-fazhnii min baini yadayya wa min khalfii wa ‘an yamiinii wa ‘an syimaalii wa min fawqii, wa a’uudzu bi’azhamatika an ughtaala min tahtii.',
      arti: 'Ya Allah, sesungguhnya aku memohon keselamatan di dunia dan akhirat. Ya Allah, sesungguhnya aku memohon ampunan dan keselamatan dalam agamaku, duniaku, keluargaku, dan hartaku. Ya Allah, tutupilah auratku (kekurangan dan aibku) dan tenangkanlah rasa takutku. Ya Allah, jagalah aku dari depan, belakang, kanan, kiri, dan dari atasku. Dan aku berlindung dengan keagungan-Mu dari disambar dari bawahku.',
      faedah: 'Rasulullah SAW tidak pernah meninggalkan doa ini setiap pagi dan sore hari. (HR. Abu Daud no. 5074, Ibnu Majah no. 3871)',
      targetCount: 1,
      waktu: 'pagi',
    ),
    DzikirItem(
      id: 7,
      judul: 'Doa Mengharap Ridha Allah & Islam',
      arab: 'رَضِيتُ بِاللَّهِ رَبًّا، وَبِالْإِسْلَامِ دِينًا، وَبِمُحَمَّدٍ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ نَبِيًّا',
      transliterasi: 'Radhiitu billaahi rabbaa, wa bil-islaami diinaa, wa bi-muhammadin shallallaahu ‘alaihi wa sallama nabiyyaa.',
      arti: 'Aku rela Allah sebagai Rabbku, Islam sebagai agamaku, dan Muhammad SAW sebagai Nabiku.',
      faedah: 'Barangsiapa membacanya sebanyak 3 kali setiap pagi dan petang, maka Allah pasti akan meridhainya pada hari kiamat. (HR. Abu Daud no. 5072, Ahmad 4:337)',
      targetCount: 3,
      waktu: 'pagi',
    ),
    DzikirItem(
      id: 8,
      judul: 'Doa Perlindungan dari Bahaya',
      arab: 'بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ',
      transliterasi: 'Bismillaahil-ladzii laa yadhurru ma’as-mihii syai-un fil ardhi wa laa fis-samaa-i wa huwas-samii’ul ‘aliim.',
      arti: 'Dengan nama Allah yang bersama nama-Nya tidak ada sesuatu pun yang membahayakan di bumi maupun di langit, dan Dia Maha Mendengar lagi Maha Mengetahui.',
      faedah: 'Barangsiapa membacanya 3 kali di pagi dan petang, niscaya tidak akan ada sesuatu pun yang mencelakainya. (HR. Abu Daud no. 5088, Tirmidzi no. 3388)',
      targetCount: 3,
      waktu: 'pagi',
    ),
    DzikirItem(
      id: 9,
      judul: 'Pujian Keagungan & Tasbih',
      arab: 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ، عَدَدَ خَلْقِهِ، وَرِضَا نَفْسِهِ، وَزِنَةَ عَرْشِهِ، وَمِدَادَ كَلِمَاتِهِ',
      transliterasi: 'Subhaanallaahi wa bihamdih, ‘adada khalqih, wa ridhaa nafsih, wa zinata ‘arsyih, wa midaada kalimaatih.',
      arti: 'Mahasuci Allah dan segala puji bagi-Nya, sebanyak jumlah ciptaan-Nya, menurut kerelaan diri-Nya, seberat timbangan ‘Arsy-Nya, dan sebanyak tinta kalimat-kalimat-Nya.',
      faedah: 'Pahalanya melebihi dzikir yang diucapkan berulang-ulang sejak pagi hingga siang hari. (HR. Muslim no. 2726)',
      targetCount: 3,
      waktu: 'pagi',
    ),
    DzikirItem(
      id: 10,
      judul: 'Memohon Ilmu Bermanfaat & Rezeki Halal',
      arab: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ عِلْمًا نَافِعًا، وَرِزْقًا طَيِّبًا، وَعَمَلًا مُتَقَبَّلًا',
      transliterasi: 'Allaahumma innii as-aluka ‘ilman naafi’aa, wa rizqan thayyibaa, wa ‘amalan mutaqabbalaa.',
      arti: 'Ya Allah, sesungguhnya aku memohon kepada-Mu ilmu yang bermanfaat, rezeki yang halal dan baik, serta amal yang diterima.',
      faedah: 'Dibaca rutin oleh Nabi SAW setelah salam shalat Subuh atau saat pagi hari. (HR. Ibnu Majah no. 925)',
      targetCount: 1,
      waktu: 'pagi',
    ),
    DzikirItem(
      id: 11,
      judul: 'Tasbih 100 Kali',
      arab: 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ',
      transliterasi: 'Subhaanallaahi wa bihamdih.',
      arti: 'Mahasuci Allah dan dengan memuji-Nya.',
      faedah: 'Barangsiapa mengucapkannya 100 kali sehari, dihapus dosa-dosanya meskipun sebanyak buih di lautan. (HR. Bukhari no. 6405, Muslim no. 2691)',
      targetCount: 100,
      waktu: 'pagi',
    ),
  ];

  static const List<DzikirItem> dzikirPetangList = [
    DzikirItem(
      id: 101,
      judul: 'Membaca Ayat Kursi',
      arab: 'اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۗ مَنْ ذَا الَّذِي يَشْفَعُ عِنْدَهُ إِلَّا بِإِذْنِهِ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۖ وَلَا يُحِيطُونَ بِشَيْءٍ مِنْ عِلْمِهِ إِلَّا بِمَا شَاءَ ۚ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ ۖ وَلَا يَئُودُهُ حِفْظُهُمَا ۚ وَهُوَ الْعَلِيُّ الْعَظِيمُ',
      transliterasi: 'Allahu laa ilaaha illaa huwal hayyul qayyuum, laa ta’khudzuhuu sinatuw walaa na’um, lahuu maa fis-samaawaati wa maa fil-ardh, man dzalladzii yasyfa’u ‘indahuu illaa bi-idznih, ya’lamu maa baina aydiihim wa maa khalfahum, wa laa yuhiithuuna bisyai-im min ‘ilmihii illaa bimaa syaa-a, wasi’a kursiyyuhus-samaawaati wal-ardh, wa laa ya-uuduhuu hifzhuhumaa, wa huwal ‘aliyyul ‘azhiim.',
      arti: 'Allah, tidak ada tuhan selain Dia. Yang Mahahidup, Yang terus-menerus mengurus (makhluk-Nya), tidak mengantuk dan tidak tidur. Milik-Nya apa yang ada di langit dan apa yang ada di bumi. Tidak ada yang dapat memberi syafaat di sisi-Nya tanpa izin-Nya. Dia mengetahui apa yang ada di hadapan mereka dan apa yang ada di belakang mereka, dan mereka tidak mengetahui sesuatu apa pun tentang ilmu-Nya melainkan apa yang Dia kehendaki. Kursi-Nya meliputi langit dan bumi. Dan Dia tidak merasa berat memelihara keduanya, dan Dia Mahatinggi, Mahabesar.',
      faedah: 'Barangsiapa membacanya di petang hari, ia akan dilindungi dari gangguan jin hingga pagi hari. (HR. Al-Hakim 1:562, Shahih At-Targhib no. 655)',
      targetCount: 1,
      waktu: 'petang',
    ),
    DzikirItem(
      id: 102,
      judul: 'Membaca Surat Al-Ikhlas, Al-Falaq, An-Naas',
      arab: 'قُلْ هُوَ اللَّهُ أَحَدٌ ﴿١﴾ اللَّهُ الصَّمَدُ ﴿٢﴾ لَمْ يَلِدْ وَلَمْ يُولَدْ ﴿٣﴾ وَلَمْ يَكُنْ لَهُ كُفُوًا أَحَدٌ ﴿٤﴾\n\nقُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ﴿١﴾ مِنْ شَرِّ مَا خَلَقَ ﴿٢﴾ وَمِنْ شَرِّ غَاسِقٍ إِذَا وَقَبَ ﴿٣﴾ وَمِنْ شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ ﴿٤﴾ وَمِنْ شَرِّ حَاسِدٍ إِذَا حَسَدَ ﴿٥﴾\n\nقُلْ أَعُوذُ بِرَبِّ النَّاسِ ﴿١﴾ مَلِكِ النَّاسِ ﴿٢﴾ إِلَٰهِ النَّاسِ ﴿٣﴾ مِنْ شَرِّ الْوَسْوَاسِ الْخَنَّاسِ ﴿٤﴾ الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ ﴿٥﴾ مِنَ الْجِنَّةِ وَالنَّاسِ ﴿٦﴾',
      transliterasi: 'Membaca surat Al-Ikhlas, Al-Falaq, dan An-Naas masing-masing sebanyak 3 kali.',
      arti: 'Dengan menyebut nama Allah Yang Maha Pengasih lagi Maha Penyayang. (Surat Al-Ikhlas, Al-Falaq, dan An-Naas).',
      faedah: 'Barangsiapa membacanya sebanyak 3 kali ketika petang dan pagi hari, maka segala sesuatu akan dicukupkan untuknya dan terjaga dari marabahaya. (HR. Abu Daud no. 5082, Tirmidzi no. 3575)',
      targetCount: 3,
      waktu: 'petang',
    ),
    DzikirItem(
      id: 103,
      judul: 'Doa Memasuki Waktu Petang',
      arab: 'أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ، رَبِّ أَسْأَلُكَ خَيْرَ مَا فِي هَٰذِهِ اللَّيْلَةِ وَخَيْرَ مَا بَعْدَهَا، وَأَعُوذُ بِكَ مِنْ شَرِّ مَا فِي هَٰذِهِ اللَّيْلَةِ وَشَرِّ مَا بَعْدَهَا، رَبِّ أَعُوذُ بِكَ مِنَ الْكَسَلِ وَسُوءِ الْكِبَرِ، رَبِّ أَعُوذُ بِكَ مِنْ عَذَابٍ فِي النَّارِ وَعَذَابٍ فِي الْقَبْرِ',
      transliterasi: 'Amsainaa wa amsal mulku lillaahi wal hamdu lillaah, laa ilaaha illallaahu wahdahu laa syariika lah, lahul mulku wa lahul hamdu wa huwa ‘alaa kulli syai-in qadiir. Rabbi as-aluka khaira maa fii haadzihil lailati wa khaira maa ba’dahaa, wa a’uudzu bika min syarri maa fii haadzihil lailati wa syarri maa ba’dahaa. Rabbi a’uudzu bika minal kasali wa suu-il kibar, Rabbi a’uudzu bika min ‘adzaabin fin-naari wa ‘adzaabin fil qabr.',
      arti: 'Kami telah memasuki waktu petang dan kerajaan hanya milik Allah, segala puji bagi Allah. Tidak ada ilah yang berhak disembah selain Allah semata, tiada sekutu bagi-Nya. Milik-Nya kerajaan dan bagi-Nya pujian. Dia Mahakuasa atas segala sesuatu. Wahai Rabbku, aku memohon kepada-Mu kebaikan malam ini dan kebaikan setelahnya, dan aku berlindung kepada-Mu dari kejahatan malam ini dan kejahatan setelahnya. Wahai Rabbku, aku berlindung kepada-Mu dari kemalasan dan keburukan di masa tua. Wahai Rabbku, aku berlindung kepada-Mu dari siksaan di neraka dan siksaan di kubur.',
      faedah: 'Memohon perlindungan Allah saat malam tiba dan keselamatan dari siksa kubur serta api neraka. (HR. Muslim no. 2723)',
      targetCount: 1,
      waktu: 'petang',
    ),
    DzikirItem(
      id: 104,
      judul: 'Sayyidul Istighfar Petang',
      arab: 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَٰهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَىٰ عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ',
      transliterasi: 'Allaahumma anta rabbii laa ilaaha illaa anta, khalaqtanii wa anaa ‘abduka, wa anaa ‘alaa ‘ahdika wa wa’dika mastatha’tu, a’uudzu bika min syarri maa shana’tu, abuu-u laka bini’matika ‘alayya, wa abuu-u bidzanbii faghfir lii fa-innahu laa yaghfirudz-dzunuuba illaa anta.',
      arti: 'Ya Allah, Engkau adalah Rabbku, tiada tuhan selain Engkau. Engkaulah yang menciptakanku dan aku adalah hamba-Mu. Aku akan setia pada perjanjianku dengan-Mu semampuku. Aku berlindung kepada-Mu dari keburukan yang telah kuperbuat. Aku mengakui nikmat-Mu kepadaku dan aku mengakui dosaku, maka ampunilah aku, sesungguhnya tiada yang dapat mengampuni dosa selain Engkau.',
      faedah: 'Barangsiapa membacanya di petang hari dengan keyakinan lalu meninggal di malam itu, ia termasuk penghuni surga. (HR. Bukhari no. 6306)',
      targetCount: 1,
      waktu: 'petang',
    ),
    DzikirItem(
      id: 105,
      judul: 'Doa Perlindungan Petang Hari',
      arab: 'اللَّهُمَّ بِكَ أَمْسَيْنَا، وَبِكَ أَصْبَحْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ الْمَصِيرُ',
      transliterasi: 'Allaahumma bika amsainaa, wa bika ash-bahnaa, wa bika nahyaa, wa bika namuutu, wa ilaikal mashiir.',
      arti: 'Ya Allah, dengan rahmat-Mu kami memasuki waktu petang, dengan rahmat-Mu kami memasuki waktu pagi, dengan rahmat-Mu kami hidup dan dengan rahmat-Mu kami mati, serta kepada-Mulah tempat kembali.',
      faedah: 'Doa penyerahan diri dan rasa syukur saat pergantian siang menuju malam. (HR. Tirmidzi no. 3391)',
      targetCount: 1,
      waktu: 'petang',
    ),
    DzikirItem(
      id: 106,
      judul: 'Memohon Keselamatan & Afiat Petang',
      arab: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَافِيَةَ فِي الدُّنْيَا وَالْآخِرَةِ، اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَفْوَ وَالْعَافِيَةَ فِي دِينِي وَدُنْيَايَ وَأَهْلِي وَمَالِي، اللَّهُمَّ اسْتُرْ عَوْرَاتِي وَآمِنْ رَوْعَاتِي، اللَّهُمَّ احْفَظْنِي مِنْ بَيْنِ يَدَيَّ وَمِنْ خَلْفِي وَعَنْ يَمِينِي وَعَنْ شِمَالِي وَمِنْ فَوْقِي، وَأَعُوذُ بِعَظَمَتِكَ أَنْ أُغْتَالَ مِنْ تَحْتِي',
      transliterasi: 'Allaahumma innii as-alukal ‘aafiyata fid-dunyaa wal aakhirah. Allaahumma innii as-alukal ‘afwa wal ‘aafiyata fii diinii wa dunyaaya wa ahlii wa maalii. Allaahummastur ‘awraatii wa aamin raw’aatii. Allaahummah-fazhnii min baini yadayya wa min khalfii wa ‘an yamiinii wa ‘an syimaalii wa min fawqii, wa a’uudzu bi’azhamatika an ughtaala min tahtii.',
      arti: 'Ya Allah, sesungguhnya aku memohon keselamatan di dunia dan akhirat. Ya Allah, sesungguhnya aku memohon ampunan dan keselamatan dalam agamaku, duniaku, keluargaku, dan hartaku. Ya Allah, tutupilah aibku dan tenangkanlah rasa takutku. Ya Allah, jagalah aku dari depan, belakang, kanan, kiri, dan dari atasku. Dan aku berlindung dengan keagungan-Mu dari disambar dari bawahku.',
      faedah: 'Perlindungan sempurna dari segala arah bahaya yang tak terduga di malam hari. (HR. Abu Daud no. 5074)',
      targetCount: 1,
      waktu: 'petang',
    ),
    DzikirItem(
      id: 107,
      judul: 'Doa Perlindungan dari Sengatan & Racun Hewan',
      arab: 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ',
      transliterasi: 'A’uudzu bikalimaatillaahit-taammaati min syarri maa khalaq.',
      arti: 'Aku berlindung dengan kalimat-kalimat Allah yang sempurna dari kejahatan makhluk yang Dia ciptakan.',
      faedah: 'Barangsiapa membacanya 3 kali di waktu petang, maka tidak akan ada racun atau sengatan hewan berbisa yang mencelakainya pada malam itu. (HR. Muslim no. 2709, Tirmidzi no. 3604)',
      targetCount: 3,
      waktu: 'petang',
    ),
    DzikirItem(
      id: 108,
      judul: 'Doa Perlindungan dari Bahaya',
      arab: 'بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ',
      transliterasi: 'Bismillaahil-ladzii laa yadhurru ma’as-mihii syai-un fil ardhi wa laa fis-samaa-i wa huwas-samii’ul ‘aliim.',
      arti: 'Dengan nama Allah yang bersama nama-Nya tidak ada sesuatu pun yang membahayakan di bumi maupun di langit, dan Dia Maha Mendengar lagi Maha Mengetahui.',
      faedah: 'Terlindung dari marabahaya mendadak sampai keesokan harinya. (HR. Abu Daud no. 5088, Tirmidzi no. 3388)',
      targetCount: 3,
      waktu: 'petang',
    ),
    DzikirItem(
      id: 109,
      judul: 'Doa Mengharap Ridha Allah & Islam',
      arab: 'رَضِيتُ بِاللَّهِ رَبًّا، وَبِالْإِسْلَامِ دِينًا، وَبِمُحَمَّدٍ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ نَبِيًّا',
      transliterasi: 'Radhiitu billaahi rabbaa, wa bil-islaami diinaa, wa bi-muhammadin shallallaahu ‘alaihi wa sallama nabiyyaa.',
      arti: 'Aku rela Allah sebagai Rabbku, Islam sebagai agamaku, dan Muhammad SAW sebagai Nabiku.',
      faedah: 'Mendapat keridhaan Allah Ta’ala di hari kiamat. (HR. Abu Daud no. 5072)',
      targetCount: 3,
      waktu: 'petang',
    ),
    DzikirItem(
      id: 110,
      judul: 'Tasbih 100 Kali Petang',
      arab: 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ',
      transliterasi: 'Subhaanallaahi wa bihamdih.',
      arti: 'Mahasuci Allah dan dengan memuji-Nya.',
      faedah: 'Tidak ada seorang pun pada hari kiamat yang membawa amalan lebih utama kecuali orang yang membaca seperti itu atau lebih banyak darinya. (HR. Muslim no. 2692)',
      targetCount: 100,
      waktu: 'petang',
    ),
  ];
}
