// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr6AUsW41l3PXITnu9kN73JkyH9ZnLNyE',
    appId: '1:317872716423:web:7743dedf8c6253c6f91622',
    messagingSenderId: '317872716423',
    projectId: 'masjid-app-a497c',
    authDomain: 'masjid-app-a497c.firebaseapp.com',
    storageBucket: 'masjid-app-a497c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU7HGo1CM8RQEGEJXamrGSUAyN4qZ3LVE',
    appId: '1:317872716423:android:8c8755d608577775f91622',
    messagingSenderId: '317872716423',
    projectId: 'masjid-app-a497c',
    storageBucket: 'masjid-app-a497c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjd4kWfd4jxbWmQBfJ8k1KE2oIh6Id4vU',
    appId: '1:317872716423:ios:7bc9e2af0cc53430f91622',
    messagingSenderId: '317872716423',
    projectId: 'masjid-app-a497c',
    storageBucket: 'masjid-app-a497c.appspot.com',
    androidClientId: '317872716423-8r51gien9igj81hu3keujjmim5d4ddbp.apps.googleusercontent.com',
    iosClientId: '317872716423-7mpmhbsnml5uld2go6chp7artnorgof8.apps.googleusercontent.com',
    iosBundleId: 'com.mesjidApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjd4kWfd4jxbWmQBfJ8k1KE2oIh6Id4vU',
    appId: '1:317872716423:ios:be3c6e071f091918f91622',
    messagingSenderId: '317872716423',
    projectId: 'masjid-app-a497c',
    storageBucket: 'masjid-app-a497c.appspot.com',
    androidClientId: '317872716423-8r51gien9igj81hu3keujjmim5d4ddbp.apps.googleusercontent.com',
    iosClientId: '317872716423-i2pb1k3j0pi4ua751pjii02ur6qvb05i.apps.googleusercontent.com',
    iosBundleId: 'com.mesjidApp.RunnerTests',
  );
}
