// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB12LB5PUmpsL0Fluw4qvmuiPHY6wVhz5E',
    appId: '1:878574490380:web:72e72804d3cfaabfe06f29',
    messagingSenderId: '878574490380',
    projectId: 'mesjid-app',
    authDomain: 'mesjid-app.firebaseapp.com',
    storageBucket: 'mesjid-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnQBXg_BJozd55FUYe16KG5julGyqpIHE',
    appId: '1:878574490380:android:4a18ade3d4add018e06f29',
    messagingSenderId: '878574490380',
    projectId: 'mesjid-app',
    storageBucket: 'mesjid-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZomjA_jNzw8ir1Sz45_9s9OAtOAN0pnE',
    appId: '1:878574490380:ios:e0065d98bd67b99ce06f29',
    messagingSenderId: '878574490380',
    projectId: 'mesjid-app',
    storageBucket: 'mesjid-app.appspot.com',
    iosBundleId: 'com.mesjidApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZomjA_jNzw8ir1Sz45_9s9OAtOAN0pnE',
    appId: '1:878574490380:ios:e1b2c87e04389113e06f29',
    messagingSenderId: '878574490380',
    projectId: 'mesjid-app',
    storageBucket: 'mesjid-app.appspot.com',
    iosBundleId: 'com.mesjidApp.RunnerTests',
  );
}
