-- Data Bab Shahih Bukhari (97 Bab Tematik)
-- Generated with Boundary Matan Matching for Fathul Bari/Lidwa Numbering
DELETE FROM hadits_bab WHERE namaTabel = 'bukhari';

INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 1, 'Permulaan Wahyu', 'كتاب بدء الوحي', 1, 6);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 2, 'Iman', 'كتاب الإيمان', 7, 56);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 3, 'Ilmu', 'كتاب العلم', 57, 131);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 4, 'Wudhu', 'كتاب الوضوء', 132, 239);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 5, 'Mandi', 'كتاب الغسل', 240, 284);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 6, 'Haid', 'كتاب الحيض', 285, 321);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 7, 'Tayamum', 'كتاب التيمم', 322, 335);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 8, 'Shalat', 'كتاب الصلاة', 336, 490);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 9, 'Waktu-Waktu Shalat', 'كتاب مواقيت الصلاة', 491, 567);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 10, 'Adzan', 'كتاب الأذان', 568, 826);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 11, 'Shalat Jumat', 'كتاب الجمعة', 827, 889);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 12, 'Shalat Khauf', 'كتاب صلاة الخوف', 890, 895);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 13, 'Shalat Dua Hari Raya', 'كتاب العيدين', 896, 935);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 14, 'Shalat Witir', 'كتاب الوتر', 936, 949);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 15, 'Istisqa'' (Meminta Hujan)', 'كتاب الاستسقاء', 950, 981);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 16, 'Kusuf (Gerhana)', 'كتاب الكسوف', 982, 1004);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 17, 'Sujud Qur''an', 'كتاب سجود القرآن', 1005, 1017);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 18, 'Qashar Shalat', 'كتاب تقصير الصلاة', 1018, 1052);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 19, 'Tahajjud & Shalat Malam', 'كتاب التهجد', 1053, 1112);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 20, 'Keutamaan Shalat di Masjid Makkah & Madinah', 'كتاب فضل الصلاة في مسجد مكة والمدينة', 1113, 1122);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 21, 'Beramal dalam Shalat', 'كتاب العمل في الصلاة', 1123, 1147);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 22, 'Sujud Sahwi', 'كتاب السهو', 1148, 1160);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 23, 'Jenazah', 'كتاب الجنائز', 1161, 1307);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 24, 'Zakat', 'كتاب الزكاة', 1308, 1416);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 25, 'Haji', 'كتاب الحج', 1417, 1649);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 26, 'Umrah', 'كتاب العمرة', 1650, 1678);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 27, 'Terhalang Haji (Muhshar)', 'كتاب المحصر', 1679, 1691);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 28, 'Denda Berburu Saat Ihram', 'كتاب جزاء الصيد', 1692, 1733);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 29, 'Keutamaan Kota Madinah', 'كتاب فضائل المدينة', 1734, 1757);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 30, 'Puasa', 'كتاب الصوم', 1758, 1767);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 31, 'Shalat Tarawih', 'كتاب صلاة التراويح', 1768, 1874);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 32, 'Keutamaan Lailatul Qadar', 'كتاب فضل ليلة القدر', 1875, 1884);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 33, 'I''tikaf', 'كتاب الاعتكاف', 1885, 1905);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 34, 'Jual Beli', 'كتاب البيوع', 1906, 2084);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 35, 'Salam (Jual Beli Pesanan)', 'كتاب السلم', 2085, 2096);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 36, 'Asy-Syuf''ah', 'كتاب الشفعة', 2097, 2099);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 37, 'Ijarah (Sewa Menyewa)', 'كتاب الإجارة', 2100, 2124);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 38, 'Hawalah (Pengalihan Hutang)', 'كتاب الحوالة', 2125, 2126);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 39, 'Kafalah (Jaminan Hutang)', 'كتاب الكفالة', 2127, 2134);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 40, 'Wakalah (Perwakilan)', 'كتاب الوكالة', 2135, 2151);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 41, 'Muzara''ah (Bercocok Tanam)', 'كتاب المزارعة', 2152, 2179);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 42, 'Pengairan & Pembagian Air', 'كتاب المساقاة والشرب', 2180, 2209);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 43, 'Hutang Piutang & Kepailitan', 'كتاب الاستقراض وأداء الديون', 2210, 2232);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 44, 'Khusumat (Perselisihan)', 'كتاب الخصومات', 2233, 2247);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 45, 'Luqathah (Barang Temuan)', 'كتاب اللقطة', 2248, 2259);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 46, 'Kezaliman & Ghasab', 'كتاب المظالم والغصب', 2260, 2302);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 47, 'Syirkah (Kemitraan/Kongsi)', 'كتاب الشركة', 2303, 2324);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 48, 'Rahn (Gadai)', 'كتاب الرهن', 2325, 2332);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 49, 'Pembebasan Budak', 'كتاب العتق', 2333, 2350);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 50, 'Mukatab', 'كتاب المكاتب', 2351, 2377);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 51, 'Hibah & Hadiah', 'كتاب الهبة وفضلها', 2378, 2442);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 52, 'Saksi-Saksi', 'كتاب الشهادات', 2443, 2492);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 53, 'Perdamaian (Shulh)', 'كتاب الصلح', 2493, 2511);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 54, 'Syarat-Syarat', 'كتاب الشروط', 2512, 2532);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 55, 'Wasiat', 'كتاب الوصايا', 2533, 2573);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 56, 'Jihad & Ekspedisi', 'كتاب الجهاد والسير', 2574, 2860);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 57, 'Khumus (Seperlima Rampasan Perang)', 'كتاب فرض الخمس', 2861, 2922);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 58, 'Jizyah & Gencatan Senjata', 'كتاب الجزية والموادعة', 2923, 2951);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 59, 'Awal Penciptaan Makhluk', 'كتاب بدء الخلق', 2952, 3032);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 60, 'Kisah Para Nabi', 'كتاب أحاديث الأنبياء', 3033, 3156);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 61, 'Manaqib (Keutamaan & Sifat)', 'كتاب المناقب', 3157, 3237);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 62, 'Keutamaan Para Shahabat', 'كتاب فضائل أصحاب النبي', 3238, 3337);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 63, 'Keutamaan Kaum Anshar', 'كتاب مناقب الأنصار', 3338, 3484);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 64, 'Peperangan Nabi (Al-Maghazi)', 'كتاب المغازي', 3485, 3808);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 65, 'Tafsir Al-Qur''an', 'كتاب التفسير', 3809, 4290);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 66, 'Keutamaan Al-Qur''an', 'كتاب فضائل القرآن', 4291, 4369);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 67, 'Nikah', 'كتاب النكاح', 4370, 4544);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 68, 'Thalaq (Perceraian)', 'كتاب الطلاق', 4545, 4626);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 69, 'Nafkah Keluarga', 'كتاب النفقات', 4627, 4648);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 70, 'Makanan & Hidangan', 'كتاب الأطعمة', 4649, 4739);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 71, 'Aqiqah', 'كتاب العقيقة', 4740, 4747);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 72, 'Sembelihan & Berburu', 'كتاب الذبائح والصيد', 4748, 4813);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 73, 'Qurban (Udhiyah)', 'كتاب الأضاحي', 4814, 4841);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 74, 'Minuman', 'كتاب الأشربة', 4842, 4903);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 75, 'Menjenguk Orang Sakit', 'كتاب المرضى', 4904, 4940);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 76, 'Pengobatan (Thibbun Nabawi)', 'كتاب الطب', 4941, 5031);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 77, 'Pakaian & Perhiasan', 'كتاب اللباس', 5032, 5207);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 78, 'Adab & Akhlak', 'كتاب الأدب', 5208, 5453);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 79, 'Isti''dzan (Meminta Izin)', 'كتاب الاستئذان', 5454, 5523);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 80, 'Doa-Doa (Ad-Da''awat)', 'كتاب الدعوات', 5524, 5627);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 81, 'Ar-Riqaq (Pelelembut Hati)', 'كتاب الرقاق', 5628, 5779);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 82, 'Qadar (Takdir Allah)', 'كتاب القدر', 5780, 5805);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 83, 'Sumpah & Nadzar', 'كتاب الأيمان والنذور', 5806, 5880);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 84, 'Kafarat Sumpah', 'كتاب كفارات الأيمان', 5881, 5894);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 85, 'Faraidh (Hukum Waris)', 'كتاب الفرائض', 5895, 5940);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 86, 'Hudud (Hukum Pidana Islam)', 'كتاب الحدود', 5941, 6020);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 87, 'Diyat (Tebusan Darah)', 'كتاب الديات', 6021, 6072);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 88, 'Mengajak Bertaubat Orang Murtad', 'كتاب استتابة المرتدين', 6073, 6092);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 89, 'Ikrah (Pemaksaan)', 'كتاب الإكراه', 6093, 6104);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 90, 'Hilah (Tipu Daya)', 'كتاب الحيل', 6105, 6132);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 91, 'Ta''bir Mimpi', 'كتاب التعبير', 6133, 6191);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 92, 'Fitnah Akhir Zaman', 'كتاب الفتن', 6192, 6269);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 93, 'Ahkam (Hukum Peradilan & Pemerintahan)', 'كتاب الأحكام', 6270, 6350);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 94, 'Angan-Angan & Harapan', 'كتاب التمني', 6351, 6370);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 95, 'Berita Ahad (Khabar Wahid)', 'كتاب أخبار الآحاد', 6371, 6387);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 96, 'Berpegang Teguh pada Al-Qur''an & As-Sunnah', 'كتاب الاعتصام بالكتاب والسنة', 6388, 6469);
INSERT INTO hadits_bab (namaTabel, urutan, nama, namaArab, noAwal, noAkhir) VALUES ('bukhari', 97, 'Tauhid', 'كتاب التوحيد', 6470, 6638);
